name = "cards-on-the-grid-backend"
main = "packages/backend/src/worker.ts"
compatibility_date = "2026-02-19"
workers_dev = true

# API auth token: set this with
# `wrangler secret put API_BEARER_TOKEN`

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]
